#!/bin/bash
# A script to allow building multiple targets from a single Dockerfile such
# that the repository does not need a separate Dockerfile for each build

# The differentiation between targets is done by looking for whether
# the image tag ends with "devel"


if [[ $DOCKER_TAG == *devel ]]
  then
    TARGET="sdk-devel";
  else
    TARGET="sdk-runtime";
fi


docker buildx build --target=$TARGET -f $DOCKERFILE_PATH -t $IMAGE_NAME .

